# action.yml
name: 'ocicl'
description: 'Publish an ocicl artifact'
inputs:
  gpg_signing_key:
    required: true
  gpg_public_key:
    required: true
  dockerhub_password:
    required: true
  llm_api_key:
    required: true
runs:
  using: "composite"
  steps:
    - uses: oras-project/setup-oras@v1
    - shell: bash
      run: oras version
    - uses: actions/checkout@v4
    - shell: bash
      run: rm -rf */.qlot
    - uses: actions/cache@v4
      with:
        path:
          ocicl
          ~/.cache/common-lisp
        key: ${{ runner.os }}-ocicl
        restore-keys: |
          ${{ runner.os }}-ocicl
    - name: Run
      shell: bash
      run: podman run --rm --volume $(pwd):/github/workspace:z ghcr.io/ocicl/ocicl-sandbox:latest
    - run: |
        set -x
        retry_command0() {
          local -r cmd="$@"
          local -i attempt=0
          local -i max_attempts=5
          local -i sleep_time=1  # Initial backoff delay in seconds

          until $cmd; do
              attempt+=1
              if (( attempt > max_attempts )); then
                  echo "The command has failed after $max_attempts attempts."
                  return 1
              fi
              echo "The command has failed. Retrying in $sleep_time seconds..."
              sleep $sleep_time
              sleep_time=$((sleep_time * 2))  # Double the backoff delay each time
          done
        }
        NAME=$(cat NAME)
        SYSTEMS=$(cat SYSTEMS)
        VERSION=$(cat VERSION)
        cd src
        echo ${{ github.token }} | oras login ghcr.io -u ${{ github.actor }} --password-stdin
        echo $DOCKERHUB_PASSWORD | oras login docker.io -u ocicl --password-stdin
        pwd
        ls -l
        for S in ${SYSTEMS}; do
          S=$(echo ${S} | sed 's/+$/_plus/g' | sed 's/+/_plus_/g')
          S=$(echo ${S} | sed 's/\//_slash_/g')
          retry_command0 oras push ghcr.io/ocicl/${S}:${VERSION} ${NAME}-${VERSION}.tar.gz:application/vnd.ocicl.lisp-system.tgz
          retry_command0 oras tag ghcr.io/ocicl/${S}:${VERSION} latest
          retry_command0 oras push docker.io/ocicl/${S}:${VERSION} ${NAME}-${VERSION}.tar.gz:application/vnd.ocicl.lisp-system.tgz
          retry_command0 oras tag docker.io/ocicl/${S}:${VERSION} latest
        done
        echo ${VERSION} > ~/_00_OCICL_VERSION
        echo ${NAME} > ~/_00_OCICL_NAME
      shell: bash
      env:
        DOCKERHUB_PASSWORD: '${{ inputs.dockerhub_password }}'
    - name: Import GPG key
      run: |
        echo $GPG_SIGNING_KEY | base64 -d | gpg --batch --import
        echo $GPG_PUBLIC_KEY | base64 -d > pub.key
      shell: bash
      env:
        GPG_SIGNING_KEY: '${{ inputs.gpg_signing_key }}'
        GPG_PUBLIC_KEY: '${{ inputs.gpg_public_key }}'
    - name: Sign the published artifact
      if: ${{ github.event_name != 'pull_request' }}
      env:
        LLM_API_KEY: '${{ inputs.llm_api_key }}'
      run: |
        retry_command() {
          local -r cmd="$@"
          local -i attempt=0
          local -i max_attempts=5
          local -i sleep_time=1  # Initial backoff delay in seconds

          until $cmd; do
              attempt+=1
              if (( attempt > max_attempts )); then
                  echo "The command has failed after $max_attempts attempts."
                  return 1
              fi
              echo "The command has failed. Retrying in $sleep_time seconds..."
              sleep $sleep_time
              sleep_time=$((sleep_time * 2))  # Double the backoff delay each time
          done
        }
        set -x
        NOTE="--annotation \"org.opencontainers.image.source=https://github.com/ocicl/REPO=\""
        NAME=$(cat NAME)
        FILE=$(cd src; ls ${NAME}-*.tar.gz)
        gpg -k
        (cd src; sha256sum ${NAME}-*.tar.gz > ../tarball.sha256sum)
        gpg --armor -u "ocicl-tarball-signer" --output ${FILE}.sha256sum.sig --detach-sig tarball.sha256sum
        for S in $(cat SYSTEMS); do
          S=$(echo ${S} | sed 's/+$/_plus/g' | sed 's/+/_plus_/g')
          S=$(echo ${S} | sed 's/\//_slash_/g')
          retry_command oras push ghcr.io/ocicl/${S}.sha256sum.sig:latest ${FILE}.sha256sum.sig:application/vnd.ocicl.lisp-system.sig
          retry_command oras tag ghcr.io/ocicl/${S}.sha256sum.sig:latest $(cat ~/_00_OCICL_VERSION)
          retry_command oras push docker.io/ocicl/${S}.sha256sum.sig:latest ${FILE}.sha256sum.sig:application/vnd.ocicl.lisp-system.sig
          retry_command oras tag docker.io/ocicl/${S}.sha256sum.sig:latest $(cat ~/_00_OCICL_VERSION)
        done
        retry_command podman run --rm --volume $(pwd):/github/workspace:z ghcr.io/ocicl/ocicl-sandbox:latest rekor-cli upload --timeout 240s --signature /github/workspace/${FILE}.sha256sum.sig --public-key /github/workspace/pub.key --artifact /github/workspace/tarball.sha256sum

        # Generate the change description
        retry_command podman run --rm -e LLM_API_KEY=$LLM_API_KEY --volume $(pwd):/github/workspace:z ghcr.io/ocicl/ocicl-sandbox:latest make-compare.sh
        echo "-----------------------------------"
        pwd
        ls -l
        echo "-----------------------------------"
        if test -f ./changes.txt; then
          mv ./changes.txt ${NAME}-changes.txt
          for S in $(cat SYSTEMS); do
            S=$(echo ${S} | sed 's/+$/_plus/g' | sed 's/+/_plus_/g')
            S=$(echo ${S} | sed 's/\//_slash_/g')
            retry_command oras push ghcr.io/ocicl/${S}-changes.txt:$(cat ~/_00_OCICL_VERSION) ${NAME}-changes.txt:application/vnd.ocicl.lisp-system.changes.txt
            retry_command oras push docker.io/ocicl/${S}-changes.txt:$(cat ~/_00_OCICL_VERSION) ${NAME}-changes.txt:application/vnd.ocicl.lisp-system.changes.txt
          done
        fi
      shell: bash
